# Generated by Django 4.0.4 on 2022-05-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='period',
            new_name='name',
        ),
    ]
