# Generated by Django 4.0.4 on 2022-05-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_instructor_instructor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='icon_id',
        ),
    ]
